-- MySQL Script generated by MySQL Workbench
-- 10/03/15 12:02:02
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fabricante` (
  `IdFabricante` INT NOT NULL AUTO_INCREMENT,
  `NombreFabrica` VARCHAR(45) NULL,
  `TipoDeRol` VARCHAR(45) NULL,
  `Modalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`IdFabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ATC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ATC` (
  `IdATC` INT NULL AUTO_INCREMENT,
  `DescripcionATC` VARCHAR(45) NULL,
  `Concentracion` VARCHAR(45) NULL,
  PRIMARY KEY (`IdATC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalleProducto` (
  `IdDetalleProducto` INT NOT NULL AUTO_INCREMENT,
  `NombreProducto` VARCHAR(45) NULL,
  `RegistroSanitario` VARCHAR(45) NULL,
  `Cantidad` INT NULL,
  `DescripcionComercial` VARCHAR(45) NULL,
  `UnidadMedida` VARCHAR(45) NULL,
  `MuestraMedica` VARCHAR(45) NULL,
  `ViaDeAdministracion` VARCHAR(45) NULL,
  `FormaFarmaceutica` VARCHAR(45) NULL,
  `PrincipioActivo` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  `Fabricante_IdFabricante` INT NOT NULL,
  `ATC_IdATC` INT NOT NULL,
  `Estado_IdEstado` INT NOT NULL,
  `EstadoRegistro` VARCHAR(45) NULL,
  `FechaActividad` DATETIME NULL,
  `FechaInactividad` DATETIME NULL,
  `FechaVencimiento` DATETIME NULL,
  `FechaExpedicion` DATETIME NULL,
  PRIMARY KEY (`IdDetalleProducto`),
  INDEX `fk_DetalleProducto_Fabricante1_idx` (`Fabricante_IdFabricante` ASC),
  INDEX `fk_DetalleProducto_ATC1_idx` (`ATC_IdATC` ASC),
  CONSTRAINT `fk_DetalleProducto_Fabricante1`
    FOREIGN KEY (`Fabricante_IdFabricante`)
    REFERENCES `mydb`.`Fabricante` (`IdFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleProducto_ATC1`
    FOREIGN KEY (`ATC_IdATC`)
    REFERENCES `mydb`.`ATC` (`IdATC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `IdInventario` INT NULL,
  `Stock` INT NULL,
  `DetalleProducto_IdDetalleProducto` INT NOT NULL,
  PRIMARY KEY (`IdInventario`),
  INDEX `fk_Inventario_DetalleProducto_idx` (`DetalleProducto_IdDetalleProducto` ASC),
  CONSTRAINT `fk_Inventario_DetalleProducto`
    FOREIGN KEY (`DetalleProducto_IdDetalleProducto`)
    REFERENCES `mydb`.`DetalleProducto` (`IdDetalleProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `IdEmpleado` INT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Salario` VARCHAR(45) NOT NULL,
  `Ventas` VARCHAR(45) NOT NULL,
  `Cedula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Cedula` VARCHAR(45) NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `IdFactura` INT NOT NULL,
  `Fecha` DATETIME NULL,
  `Total` FLOAT NULL,
  `Empleado_IdEmpleado` INT NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  PRIMARY KEY (`IdFactura`),
  INDEX `fk_Factura_Empleado1_idx` (`Empleado_IdEmpleado` ASC),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_IdCliente` ASC),
  CONSTRAINT `fk_Factura_Empleado1`
    FOREIGN KEY (`Empleado_IdEmpleado`)
    REFERENCES `mydb`.`Empleado` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalleFactura` (
  `IdDetalleFactura` INT NOT NULL,
  `Factura_IdFactura` INT NOT NULL,
  `DetalleProducto_IdDetalleProducto` INT NOT NULL,
  PRIMARY KEY (`IdDetalleFactura`),
  INDEX `fk_DetalleFactura_Factura1_idx` (`Factura_IdFactura` ASC),
  INDEX `fk_DetalleFactura_DetalleProducto1_idx` (`DetalleProducto_IdDetalleProducto` ASC),
  CONSTRAINT `fk_DetalleFactura_Factura1`
    FOREIGN KEY (`Factura_IdFactura`)
    REFERENCES `mydb`.`Factura` (`IdFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleFactura_DetalleProducto1`
    FOREIGN KEY (`DetalleProducto_IdDetalleProducto`)
    REFERENCES `mydb`.`DetalleProducto` (`IdDetalleProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
